apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: argo  
type: Opaque
data:
  username: YWRtaW4=
  password: Z2l0aHViX3BhdF8xMUJKS1ZLUFEwVThJNmJ2T1ZvRXB3XzVnT1NSMmdZOG5UYVNsbWdCWE15YnZB
  github-token: OEI0VnFpVkJZVU01M0o2SWRJMDZVNElGNkJVTmRQOEluRzRZ