service:
  enabled: true
  type: NodePort  # Change to LoadBalancer if needed

# Configure Grafana to use Prometheus as a data source
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80  # Update based on your Prometheus service
        isDefault: true

