apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-boot-demo-pvc
  namespace: spring-boot-demo-namespace  # Specify the namespace here
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode as needed
  resources:
    requests:
      storage: 1Gi  # Specify the storage size
  storageClassName: standard  # Use the cephfs storage class

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  namespace: spring-boot-demo-namespace  # Specify the namespace here
  labels:
    app: spring-boot-demo
spec:
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
      annotations:                  
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"   
        prometheus.io/path: "/actuator/prometheus" 
    spec:
      imagePullSecrets:
        - name: docker-registry-secret  # Refer to the secret here
      containers:
        - name: spring-boot-demo
          image: harbor.devbsfintech23.com/test-discovery/simple-spring:test
          ports:
            - containerPort: 8080
          volumeMounts:  # Mount the PVC here
            - mountPath: /data  # Path where the volume will be mounted in the container
              name: spring-boot-demo-storage  # Name of the volume
      volumes:  # Define the volume
        - name: spring-boot-demo-storage
          persistentVolumeClaim:
            claimName: spring-boot-demo-pvc  # Reference the PVC created above

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo
  namespace: spring-boot-demo-namespace  # Specify the namespace here
  labels:
    app: spring-boot-demo
  annotations:                    
    prometheus.io/discover: "true" 
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"   
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-demo
